upload JUNIT-XML from CI-build

diff --git a/.github/workflows/build_msvc.yml b/.github/workflows/build_msvc.yml
--- a/.github/workflows/build_msvc.yml
+++ b/.github/workflows/build_msvc.yml
@@ -2,6 +2,9 @@ name: BUILD-MSVC-CI
 
 on: [push, pull_request]
 
+permissions:
+  checks: write
+  
 jobs:
   ci:
     if: >-
@@ -24,35 +27,24 @@ jobs:
       run: |
         mkdir install
         cmake -G "${{matrix.gen}}" -A ${{matrix.arch}} -DTinyTIFF_BUILD_SHARED_LIBS=${{matrix.shared}} -DTinyTIFF_BUILD_STATIC_LIBS=${{matrix.static}} -DBUILD_SHARED_LIBS=${{matrix.shared}} "-DCMAKE_INSTALL_PREFIX=./install" -B build
-    - name: Build Debug
-      run: |
-          cmake --build build --config Debug --verbose
     - name: Build Release
       run: |
            cmake --build build --config Release --verbose           
-    - name: Install
+    - name: Install Release
       run: |
         cmake --install build --config Release
         cd install
         ls -R
     - name: Run Release tests
       run: |
-        cd build
-        cd output
-        cd Release
+        cd install
+        cd bin
         pwd
         ls 
         .\tinytiffwriter_test --simple
         .\tinytiffreader_test --simple
-#        ctest -C Release  -LE explicitonly  --output-on-failure
-    - name: Run Debug tests
-      run: |
-        cd build
-        cd output
-        cd Debug
-        pwd
-        ls 
-        .\tinytiffwriter_test --simple
-        .\tinytiffreader_test --simple
-#        ctest -C Debug  -LE explicitonly  --output-on-failure
-
+     - name: Publish Test Report
+            uses: mikepenz/action-junit-report@v4
+            if: success() || failure() # always run even if the previous step fails
+            with:
+              report_paths: '**/install/bin/*.xml'
